version: 2.0

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node

jobs:
  checkout-code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  yarn:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            - v1-yarn-
      - run: yarn --frozen-lockfile
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules

  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn audit

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn lint

  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: git config --global user.email "me@mortik.xyz"
      - run: git config --global user.name "Marten Klitzke"
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "a4:a1:a7:a9:54:bc:b4:37:db:73:92:04:bc:57:f3:b2"
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/app/.npmrc
      - run: ./scripts/release.sh

workflows:
  version: 2
  check:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only: main
    jobs:
      - checkout-code
      - yarn:
          requires:
            - checkout-code
      - audit:
          requires:
            - yarn
      - lint:
          requires:
            - yarn
      - tests:
          requires:
            - yarn
  main:
    jobs:
      - checkout-code
      - yarn:
          requires:
            - checkout-code
      - audit:
          requires:
            - yarn
      - lint:
          requires:
            - yarn
      - tests:
          requires:
            - yarn
      - deploy:
          requires:
            - audit
            - lint
            - tests
          filters:
            branches:
              only: main
